# Generated by Django 4.1.6 on 2023-03-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restify", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="properties",
            name="rate_per_day",
        ),
        migrations.AddField(
            model_name="properties",
            name="postal_code",
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="properties",
            name="max_guests",
            field=models.PositiveIntegerField(),
        ),
    ]
